#!/bin/bash

#
# Generate monthly accounting statistics from Torque
#

# Configure this if necessary:
BINDIR=/usr/local/bin
AWK=/bin/gawk
TORQUEHOME=/var/spool/torque

# CONFIGURE THIS for your local environment:
# People who will receive the report
SUBSCRIBERS=root@localhost
SYSTEMNAME="Torque cluster"

MONTH_NUMBER=`/bin/date +%m`
PREV_MONTH_NUMBER=`echo $MONTH_NUMBER | $AWK '{printf("%2.2d\n", $1 - 1)}'`
YEAR=`/bin/date +%Y`
START_YEAR=$YEAR

if [ $PREV_MONTH_NUMBER = "00" ]; then
  PREV_MONTH_NUMBER=12
  START_YEAR=`expr $START_YEAR - 1`
fi

PREV_MONTH=`${BINDIR}/mm2month $PREV_MONTH_NUMBER`

# Go the the Torque accounting directory
cd ${TORQUEHOME}/server_priv/accounting

# Accounting filenames are YYYYMMDD:
MONTHFILES=${START_YEAR}${PREV_MONTH_NUMBER}??
REPORT=Report.${PREV_MONTH}_${START_YEAR}
${BINDIR}/pbsacct ${MONTHFILES} > ${REPORT}
# Append the group-wise accounting summary
${BINDIR}/pbsacct -G ${MONTHFILES} >> ${REPORT}
# Append the node accounting summary
${BINDIR}/pbsnodect ${MONTHFILES} >> ${REPORT}

# Local addition:
# Make group accounting sub-reports
for g in mek mic hammer comala compuj erdtu cmd
do
	echo >> ${REPORT}
	echo "====================================================" >> ${REPORT}
	echo >> ${REPORT}
	echo Accounting for group $g >> ${REPORT}
	${BINDIR}/pbsacct -g $g ${MONTHFILES} >> ${REPORT}
done

# Move global history files to private directory.
# SAVEDIR=${PREV_MONTH}_${START_YEAR}
# mkdir ${SAVEDIR}
# mv ${MONTHFILES} ${SAVEDIR}
# gzip ${SAVEDIR}/*

# Mail monthly report to a list of users (acct_list in /etc/aliases)
cat ${REPORT} | /bin/mail -s "$SYSTEMNAME batch job accounting for $PREV_MONTH $START_YEAR" ${SUBSCRIBERS}
